apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dhoq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dhoq
    app.kubernetes.io/part-of: ci10t-786-0063-app
  name: devfile-sample-dhoq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-dhoq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-dhoq
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0063-tenant/ci10t-786-0063-app/devfile-sample-dhoq@sha256:5bf20f65864175d602a99084f4e99fefbabcd88c412cbdacc680d9bfa33b5500
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
