apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dhoq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0063-tenant/ci10t-786-0063-app/devfile-sample-dhoq@sha256:5bf20f65864175d602a99084f4e99fefbabcd88c412cbdacc680d9bfa33b5500
        name: my-nodejs
        resources: {}
status: {}
